---

services: docker

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: centos6
    init: /sbin/init
    run_opts: ""
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: ubuntu1404
    init: /sbin/init
    run_opts: ""
  - distro: ubuntu1204
    init: /sbin/init
    run_opts: ""

before_install:
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp)

  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/repo-xcat:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible localhost -m setup'

  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/repo-xcat/tests/test.yml --syntax-check'

  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/repo-xcat/tests/test.yml'

  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/repo-xcat/tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm yum -y install xCAT'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

...
